export const ADD_GROUP = 'ADD GROUP';
export const EDIT_GROUP = 'EDIT GROUP';
export const DELETE_GROUP = 'DELETE GROUP';
export const SELECT_GROUP = 'SELECT GROUP';
export const CHANGE_CUURENT_GROUP_NAME = 'CHANGE CURRENT GROUP NAME';
export const ADD_USER_TO_CURRENT_GROUP = 'ADD USER TO CURRENT GROUP';
export const REMOVE_USER_FROM_CURRENT_GROUP = 'REMOVE USER FROM CURRENT GROUP';
export const SELECT_USER_IN_CURRENT_GROUP = 'SELECT USER IN CURRENT GROUP';