export const ADD_USER = 'ADD USER';
export const EDIT_USER = 'EDIT USER';
export const SELECT_USER = 'SELECT USER';
export const DELETE_USER = 'DELETE USER';
export const CHANGE_CURRENT_USER_NAME = 'CHANGE CURRENT USER NAME';
export const CHANGE_CURRENT_USER_GROUPS = 'CHANGE CURRENT USER GROUPS';
export const UPDATE_USERS_FOR_GROUP = 'UPDATE USERS FOR GROUP';